version: "3"

services:
  app:
    build: .
    entrypoint: ./.docker/entrypoint.sh
    container_name: dark-react-app
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    networks:
      - react-app

networks:
  react-app:
    driver: bridge
